// Generated by CoffeeScript 1.8.0
(function() {
  var observer;

  observer = new Object;

  observer._observeHandlers = {};

  observer.observe = function(object, property, callback) {
    var handler;
    handler = (function(_this) {
      return function(changes) {
        var change, _i, _len;
        for (_i = 0, _len = changes.length; _i < _len; _i++) {
          change = changes[_i];
          if (property === change.name) {
            callback(change.type, change.oldValue, object[property]);
          }
        }
        return void 0;
      };
    })(this);
    if (this._observeHandlers[property] == null) {
      this._observeHandlers[property] = [];
    }
    this._observeHandlers[property].push([object, handler]);
    return Object.observe(object, handler);
  };

  observer.unobserve = function(object, property) {
    var _handler, _i, _len, _object, _ref, _ref1;
    if (this._observeHandlers[property] != null) {
      _ref = this._observeHandlers[property];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        _ref1 = _ref[_i], _object = _ref1[0], _handler = _ref1[1];
        if (object === _object) {
          Object.unobserve(_object, _handler);
        }
      }
      if (this._observeHandlers[property].lenght === 0) {
        delete this._observeHandlers[property];
      }
    }
    return void 0;
  };

  window.Tools.observer = observer;

}).call(this);

//# sourceMappingURL=observer.js.map
