// Generated by CoffeeScript 1.8.0
(function() {
  var storage;

  storage = {
    save: function(key, val) {
      localStorage.setItem(key, JSON.stringify(val));
      return key;
    },
    load: function(key) {
      return JSON.parse(localStorage.getItem(key));
    },
    "delete": function(key) {
      localStorage.removeItem(key);
      return key;
    }
  };

  window.Tools.storage = storage;

}).call(this);

//# sourceMappingURL=storage.js.map
