// Generated by CoffeeScript 1.8.0
(function() {
  var deepCopy, loadByStructure, saveByStructure;

  deepCopy = Tools.deepCopy;

  saveByStructure = function(structure, isDeepCopy) {
    var backup, element, objectField, objectName, _i, _len, _ref;
    if (isDeepCopy == null) {
      isDeepCopy = false;
    }
    backup = {};
    for (objectName in structure) {
      element = structure[objectName];
      _ref = element.fields;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        objectField = _ref[_i];
        if (backup[objectName] == null) {
          backup[objectName] = {};
        }
        backup[objectName][objectField] = isDeepCopy ? deepCopy(element.obj[objectField]) : element.obj[objectField];
      }
    }
    return backup;
  };

  loadByStructure = function(structure, savedData) {
    var element, objectField, objectName, _i, _len, _ref;
    for (objectName in structure) {
      element = structure[objectName];
      _ref = element.fields;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        objectField = _ref[_i];
        element.obj[objectField] = savedData[objectName][objectField];
      }
    }
    return void 0;
  };

  window.Tools.saveByStructure = saveByStructure;

  window.Tools.loadByStructure = loadByStructure;

}).call(this);

//# sourceMappingURL=structure.js.map
