// Generated by CoffeeScript 1.7.1
(function() {
  var Controller, Model, View, deepCopy, getValScope, _Carousel;

  getValScope = function(val, scope) {
    if (scope[0] > val) {
      return scope[0];
    } else if (scope[1] < val) {
      return scope[1];
    }
    return val;
  };

  deepCopy = function(v) {
    return $.extend(true, [], v);
  };

  Model = (function() {
    function Model() {
      this.isDay = false;
      this.isGame = false;
      this.time = 0;
      this.timer = void 0;
      this.players = [];
      this.initSettings();
      this.snapshots = [];
      this.snapshotPoint = -1;
      this.levels = {
        square: [0.6, 1],
        hospital: [0.3, 0.6],
        resuscitation: [0, 0.3],
        morgue: [-10000, 0]
      };
      this.view = void 0;
      this.addSnapshot();
      void 0;
    }

    Model.prototype.initSettings = function() {
      this.settings = JSON.parse(localStorage.getItem('settings'));
      if (this.settings === null) {
        this.settings = {
          stTime: 15,
          maxAttack: 20,
          selfDestroyAttack: true,
          selfDestroyTreat: true,
          hospitalPlus10: true,
          nullResus: true
        };
        localStorage.setItem('settings', JSON.stringify(this.settings));
      }
      this.settingsDesc = {
        info: {
          type: "text",
          before: "Помните: настройки обновляются <b>сразу</b>!"
        },
        stTime: {
          type: "number",
          before: "Продолжительность дня",
          after: "мин",
          def: "20",
          help: "Если вы меняете это поле днём, то изменения вступят в силу только на <b>следующий</b> день"
        },
        maxAttack: {
          type: "number",
          before: "Максимальная атака",
          after: "%",
          def: "15"
        },
        selfDestroyAttack: {
          type: "checkbox",
          after: "Уничтожение самого себя (Атака)"
        },
        selfDestroyTreat: {
          type: "checkbox",
          after: "Уничтожение самого себя (Лечение)"
        },
        hospitalPlus10: {
          type: "checkbox",
          after: "Дополнительные +10 при лечении в госпитале"
        },
        nullResus: {
          type: "checkbox",
          after: "Обнуление количества решений при лечении в реанимации"
        },
        attackFormula: {
          type: "text",
          before: "Формула расчёта урона:<br>min (10 + Р - Н - 3 * Л, МАКСУРОН)",
          help: "Р -- кол-во решённых задач<br> Н -- кол-во нерешённых задач<br> Л -- кол-во попыток лечения<br> МАКСУРОН -- максимальный урон, см. выше"
        },
        treatFormula: {
          type: "text",
          before: "Формула расчёта лечения:<br>5 * У + Р - Н - 3 * Л - 5",
          help: "У -- кол-во решённых задач из 3-х, остальное см. выше"
        },
        github: {
          type: "text",
          before: "<a href='https://github.com/ktulhy-kun/math_gunplay'>Исходный код</a>"
        }
      };
      return void 0;
    };

    Model.prototype.setSettings = function(name, val) {
      this.settings[name] = val;
      localStorage.setItem('settings', JSON.stringify(this.settings));
      return void 0;
    };

    Model.prototype.joinView = function(view) {
      this.view = view;
    };

    Model.prototype.forwardSnapshot = function() {
      this.snapshotPoint += 1;
      this.loadSnapshot(this.snapshotPoint);
      return void 0;
    };

    Model.prototype.loadSnapshot = function(snapshotN) {
      var _ref;
      if (snapshotN == null) {
        snapshotN = this.snapshotPoint - 1;
      }
      this.snapshotPoint = snapshotN;
      _ref = this.snapshots[this.snapshotPoint], this.isGame = _ref.isGame, this.isDay = _ref.isDay, this.players = _ref.players;
      this.view.updateUI();
      return void 0;
    };

    Model.prototype.addSnapshot = function() {
      var _ref, _ref1;
      this.snapshotPoint += 1;
      [].splice.apply(this.snapshots, [(_ref = this.snapshotPoint), 9e9].concat(_ref1 = {
        'isGame': this.isGame,
        'isDay': this.isDay,
        'players': deepCopy(this.players)
      })), _ref1;
      if (this.view) {
        this.view.snapshotButtons();
      }
      return void 0;
    };

    Model.prototype.clearSnapshots = function() {
      this.snapshotPoint = -1;
      this.snapshots = [];
      this.addSnapshot();
      return void 0;
    };

    Model.prototype.setDayTimer = function() {
      this.time = this.settings.stTime * 60;
      this.view.updateTime();
      this.timer = setInterval((function(_this) {
        return function() {
          _this.time -= 1;
          if (_this.time <= 0) {
            _this.changeDayNight();
          } else {
            _this.view.updateTime();
          }
          return void 0;
        };
      })(this), 1000);
      return void 0;
    };

    Model.prototype.changeDayNight = function() {
      clearInterval(this.timer);
      if (!this.isGame) {
        this.isGame = true;
        this.isDay = true;
      } else {
        this.isDay = !this.isDay;
      }
      if (this.isDay) {
        this.setDayTimer();
      }
      this.clearSnapshots();
      this.view.updateUI();
      return void 0;
    };

    Model.prototype.setHealth = function(plN, health) {
      this.players[plN].health = getValScope(health, [0, 1]);
      return void 0;
    };

    Model.prototype.getLevel = function(plN) {
      var h, level, scope, _ref;
      if (plN !== -1) {
        h = this.players[plN].health;
        _ref = this.levels;
        for (level in _ref) {
          scope = _ref[level];
          if ((scope[0] < h && h <= scope[1])) {
            return level;
          }
        }
      }
      return void 0;
    };

    Model.prototype.getAttack = function(plN) {
      var pl;
      pl = this.players[plN];
      return (getValScope(10 + pl.solve - pl.unsolve - 3 * pl.treatment, [0, 20])) / 100;
    };

    Model.prototype.getAttackTo = function(plN, plN2) {
      if ((0 === this.players[plN].health) || ((this.getLevel(plN)) !== (this.getLevel(plN2)))) {
        return 0;
      }
      if ((!this.settings.selfDestroyAttack) && (plN === plN2)) {
        return 0;
      }
      return this.getAttack(plN);
    };

    Model.prototype.getTreat = function(plN, solved) {
      var h, pl;
      pl = this.players[plN];
      h = 5 * solved + pl.solve - pl.unsolve - 3 * pl.treatment - 5;
      if (this.settings.hospitalPlus10 && ((this.getLevel(plN)) === 'hospital')) {
        console.log("+10!");
        h += 10;
      }
      if (!this.settings.selfDestroyTreat) {
        h = getValScope(h, [0, Infinity]);
      }
      h = getValScope(h, [-Infinity, 1 - pl.health]);
      return (getValScope(h, [-Infinity, Infinity])) / 100;
    };

    Model.prototype.treat = function(plN, solved) {
      var inc, pl;
      pl = this.players[plN];
      inc = this.getTreat(plN, solved);
      this.setHealth(plN, pl.health + inc);
      if (this.settings.nullResus && ((this.getLevel(plN)) === "resuscitation")) {
        pl.treatment = 0;
      } else {
        pl.treatment += 1;
      }
      this.addSnapshot();
      this.view.treat(plN, inc);
      return void 0;
    };

    Model.prototype.hit = function(plN1, plN2) {
      var atk, pl1, pl2;
      pl1 = this.players[plN1];
      pl2 = this.players[plN2];
      atk = this.getAttackTo(plN1, plN2);
      this.setHealth(plN2, pl2.health - atk);
      pl1.solve += 1;
      this.view.hit(plN1, plN2, -atk);
      this.addSnapshot();
      return void 0;
    };

    Model.prototype.miss = function(plN1) {
      var pl1;
      pl1 = this.players[plN1].unsolve += 1;
      this.view.miss(plN1);
      this.addSnapshot();
      return void 0;
    };

    Model.prototype.addPlayer = function(name) {
      this.players.push({
        name: name,
        id: this.players.length,
        health: 1,
        solve: 0,
        unsolve: 0,
        treatment: 0
      });
      this.view.updateUI();
      return void 0;
    };

    return Model;

  })();

  View = (function() {
    function View() {
      var ind, item, items, _i, _len, _ref;
      this.elements = {
        buttons: {
          backward: $("#backward"),
          forward: $("#forward"),
          daynight: $("#daynight")
        },
        inputs: {
          newPlayer: $("#addplayer")
        },
        blocks: {
          newPlayer: $(".pl-addplayer")
        },
        carousel: {
          "this": new _Carousel($("#carousel")),
          items: [$("#item0"), $("#item1"), $("#item2"), $("#item3")]
        },
        tables: [$("#table0")],
        places: [
          {
            "this": $("#table0 > .pl-list"),
            list: []
          }
        ],
        templates: {
          players: ($("#players-template")).html(),
          place: ($("#place-template")).html()
        },
        settings: $("#settings-modal .modal-body")
      };
      this.nightMode = {
        is: false,
        selected: -1,
        attack: -1
      };
      items = this.elements.carousel.items;
      _ref = items.slice(1);
      for (ind = _i = 0, _len = _ref.length; _i < _len; ind = ++_i) {
        item = _ref[ind];
        item.html("<table id=\"table" + (ind + 1) + "\" class=\"table\"> " + this.elements.templates.players + " </table>");
        this.elements.tables.push($("#table" + (ind + 1)));
        this.elements.places.push({
          "this": $("#table" + (ind + 1) + " > .pl-list"),
          list: []
        });
      }
      void 0;
    }

    View.prototype.joinModel = function(model) {
      this.model = model;
    };

    View.prototype.joinController = function(controller) {
      this.controller = controller;
      return this.generateSettings();
    };

    View.prototype.generateSettings = function() {
      var body, def, desc, elem, help, name, sett, settDesc, _results;
      sett = this.model.settings;
      settDesc = this.model.settingsDesc;
      body = this.elements.settings;
      _results = [];
      for (name in settDesc) {
        desc = settDesc[name];
        help = desc.help ? "<p class='help-block'>" + desc.help + "</p>" : "";
        switch (desc.type) {
          case "text":
            body.append("<div class='row'> <div class='col-lg-10'> <p class='form-control-static' id='" + name + "'>" + desc.before + "</p> " + help + " </div> </div>");
            break;
          case "number":
            body.append("<div class='row'> <div class='col-lg-10'> <div class='input-group'> <span class='input-group-addon'>" + desc.before + "</span> <input id='" + name + "' type='number' class='form-control' placeholder='" + (desc.def ? desc.def : '') + "'> <span class='input-group-addon'>" + desc.after + "</span> </div> " + help + " </div> </div>");
            break;
          case "checkbox":
            body.append("<div class='row'> <div class='col-lg-10'> <div class='checkbox'> <label> <input id='" + name + "' type='checkbox'>" + desc.after + " </label> " + help + " </div> </div> </div>");
            break;
        }
        elem = $("#" + name);
        this.elements.settings[name] = elem[0];
        def = this.model.settings[name];
        this.controller.bindSettings(elem, name, desc.type, def);
        _results.push(void 0);
      }
      return _results;
    };

    View.prototype.updateUI = function() {
      this.snapshotButtons();
      if (!this.model.isGame) {
        this.beforeGameUI();
      } else {
        if (this.model.isDay) {
          this.dayUI();
        } else {
          this.nightUI();
        }
      }
      return void 0;
    };

    View.prototype.placeTest = function() {
      var listItem, place, places, _i, _len;
      places = this.elements.places;
      if (places[0].list.length < this.model.players.length) {
        for (_i = 0, _len = places.length; _i < _len; _i++) {
          place = places[_i];
          place["this"].append(this.elements.templates.place);
          listItem = place["this"].find("tr:last-child");
          listItem.hide();
          place.list.push({
            "this": listItem,
            id: listItem.find(".id"),
            name: listItem.find(".name"),
            health: listItem.find(".health"),
            attack: listItem.find(".attack"),
            tasks: listItem.find(".tasks"),
            actions: {
              "this": listItem.find(".actions"),
              solve: listItem.find(".solve"),
              unsolve: listItem.find(".unsolve"),
              treat: [listItem.find(".treat0"), listItem.find(".treat1"), listItem.find(".treat2"), listItem.find(".treat3")]
            }
          });
          place.list.slice(-1)[0].actions["this"].hide();
        }
      }
      return void 0;
    };

    View.prototype.snapshotButtons = function() {
      if (this.model.snapshotPoint !== 0) {
        this.elements.buttons.backward.show(500);
      } else {
        this.elements.buttons.backward.hide(500);
      }
      if (this.model.snapshotPoint !== (this.model.snapshots.length - 1)) {
        this.elements.buttons.forward.show(500);
      } else {
        this.elements.buttons.forward.hide(500);
      }
      return void 0;
    };

    View.prototype.beforeGameUI = function() {
      var listById;
      this.nightMode.is = false;
      listById = this.model.players;
      this.elements.carousel["this"].hideControls();
      this.elements.carousel["this"].go(0);
      this.elements.carousel["this"].pause();
      this.elements.blocks.newPlayer.show(500);
      this.elements.buttons.daynight.text("Добавление игроков");
      this.placeTest();
      this.placePlayers([listById]);
      return void 0;
    };

    View.prototype.dayUI = function() {
      var getSortF, listByHealth, listById, listBySolve, listByUnsolve;
      this.nightMode.is = false;
      this.nightMode.attack = -1;
      this.nightMode.selected = -1;
      this.elements.carousel["this"].showControls();
      this.elements.carousel["this"].overflow("hidden");
      this.elements.carousel["this"].go(0);
      this.elements.carousel["this"].start();
      this.elements.blocks.newPlayer.hide(500);
      getSortF = function(item) {
        return function(a, b) {
          return b[item] - a[item];
        };
      };
      listById = this.model.players;
      listByHealth = deepCopy(listById);
      listByHealth.sort(getSortF('health'));
      listBySolve = deepCopy(listById);
      listBySolve.sort(getSortF('solve'));
      listByUnsolve = deepCopy(listById);
      listByUnsolve.sort(getSortF('unsolve'));
      this.placePlayers([listById, listByHealth, listBySolve, listByUnsolve]);
      return void 0;
    };

    View.prototype.nightUI = function() {
      var listById;
      this.nightMode.is = true;
      this.controller.bindNight();
      this.elements.carousel["this"].hideControls();
      this.elements.carousel["this"].overflow("visible");
      this.elements.carousel["this"].go(0);
      this.elements.carousel["this"].pause();
      this.elements.blocks.newPlayer.hide(500);
      listById = this.model.players;
      this.elements.buttons.daynight.text("Ночь");
      this.placePlayers([listById]);
      return void 0;
    };

    View.prototype.placePlayers = function(lists) {
      var attackLevel, l, list, listItem, p, place, player, _i, _j, _len, _len1;
      for (l = _i = 0, _len = lists.length; _i < _len; l = ++_i) {
        list = lists[l];
        place = this.elements.places[l];
        attackLevel = this.model.getLevel(this.nightMode.attack);
        for (p = _j = 0, _len1 = list.length; _j < _len1; p = ++_j) {
          player = list[p];
          listItem = place.list[p];
          listItem.id.text(player.id + 1);
          listItem.name.text(player.name);
          if (this.nightMode.is && (p === this.nightMode.selected)) {
            listItem.health.hide();
            listItem.attack.hide();
            listItem.tasks.hide();
            listItem.actions["this"].show();
          } else {
            listItem.health.show().text((player.health * 100).toFixed(0));
            listItem.attack.show().text(((this.model.getAttack(player.id)) * 100).toFixed(0));
            listItem.tasks.show().text("" + player.solve + "/" + player.unsolve);
            listItem.actions["this"].hide();
          }
          listItem["this"].removeClass().addClass(this.model.getLevel(player.id));
          if ((this.nightMode.attack !== -1) && (attackLevel !== this.model.getLevel(p))) {
            listItem["this"].addClass("not").prop({
              "disabled": true
            });
          } else {
            listItem["this"].removeClass("not");
          }
          listItem["this"].show(500);
          void 0;
        }
        void 0;
      }
      return void 0;
    };

    View.prototype.updateTime = function() {
      var all_time, k, minutes, page_w;
      minutes = this.model.time % 60;
      minutes = minutes < 10 ? "0" + minutes : minutes;
      this.elements.buttons.daynight.text("День (" + (Math.floor(this.model.time / 60)) + ":" + minutes + ")");
      page_w = ($("html")).width();
      all_time = this.model.settings.stTime * 60;
      k = this.model.time / all_time;
      ($(".sun")).offset({
        top: 100 * (1 * k * k - 1 * k + 1.5) - 50,
        left: (1 - k) * (page_w + 150) - 100
      });
      return void 0;
    };

    View.prototype.hit = function(plN1, plN2, atk) {
      console.log("BADABOOM " + plN1 + " ====> " + plN2);
      this.nightMode.attack = -1;
      this.nightMode.selected = -1;
      this.updateUI();
      this.popup(plN2, "health", atk * 100);
      return void 0;
    };

    View.prototype.miss = function(plN) {
      console.log("PHAHAHA " + plN);
      this.nightMode.selected = -1;
      this.nightMode.attack = -1;
      this.updateUI();
      this.popup(plN, "name", "Мазила");
      return void 0;
    };

    View.prototype.treat = function(plN, inc) {
      this.nightMode.attack = -1;
      this.nightMode.selected = -1;
      this.updateUI();
      this.popup(plN, "health", inc * 100);
      return void 0;
    };

    View.prototype.popup = function(plN, selector, text) {
      var el, left, popup, top, _this;
      el = this.elements.places[0].list[plN][selector];
      left = el.offset().left + el.width() / 2;
      top = el.offset().top - el.height() / 2;
      if ($.isNumeric(text)) {
        text = text.toFixed(0);
        if (text >= 0) {
          text = "+" + text;
        }
      }
      el.append("<div id='popup' class='" + (text >= 0 ? 'green' : 'red') + "' style='opacity:0'>" + text + "</div>");
      popup = $("#popup");
      popup.offset({
        top: top,
        left: left
      });
      _this = this;
      return (popup.animate({
        opacity: [1, "swing"],
        top: ["-=20px", "linear"]
      }, 1000)).animate({
        opacity: [0, "swing"],
        top: ["-=20px", "linear"]
      }, 1000, "linear", function() {
        return popup.remove();
      });
    };

    View.prototype.attackMode = function(plN) {
      if (-1 === this.nightMode.attack) {
        this.nightMode.attack = plN;
      } else {
        this.nightMode.attack = -1;
        this.nightMode.selected = -1;
      }
      this.updateUI();
      return void 0;
    };

    View.prototype.selectMode = function(plN) {
      if (-1 !== this.nightMode.attack) {
        this.model.hit(this.nightMode.attack, plN);
      } else {
        this.nightMode.selected = plN === this.nightMode.selected ? -1 : plN;
        this.updateUI();
      }
      return void 0;
    };

    return View;

  })();

  Controller = (function() {
    function Controller() {
      this.isBindNight = 0;
    }

    Controller.prototype.joinModel = function(model) {
      this.model = model;
    };

    Controller.prototype.joinView = function(view) {
      this.view = view;
    };

    Controller.prototype.bind = function() {
      var els, input;
      els = this.view.elements;
      input = els.inputs.newPlayer;
      input.keyup((function(_this) {
        return function(e) {
          var name;
          if (13 === e.keyCode) {
            name = input.val();
            input.val("");
            _this.model.addPlayer(name);
          }
          return void 0;
        };
      })(this));
      els.buttons.daynight.click((function(_this) {
        return function() {
          _this.model.changeDayNight();
          return void 0;
        };
      })(this));
      els.buttons.forward.click((function(_this) {
        return function() {
          _this.model.forwardSnapshot();
          return void 0;
        };
      })(this));
      els.buttons.backward.click((function(_this) {
        return function() {
          _this.model.loadSnapshot();
          return void 0;
        };
      })(this));
      return void 0;
    };

    Controller.prototype.bindSettingsGenerate = function(name, type) {
      switch (type) {
        case "number":
          return (function(_this) {
            return function() {
              return _this.model.setSettings(name, _this.view.elements.settings[name].value);
            };
          })(this);
        case "checkbox":
          return (function(_this) {
            return function() {
              return _this.model.setSettings(name, _this.view.elements.settings[name].checked);
            };
          })(this);
        default:
          return (function(_this) {
            return function() {};
          })(this);
      }
    };

    Controller.prototype.bindSettings = function(elem, name, type, def) {
      elem = $("#" + name);
      switch (type) {
        case "number":
          elem.val(def);
          elem.keyup(this.bindSettingsGenerate(name, type));
          break;
        case "checkbox":
          elem[0].checked = def;
          elem.on('click', this.bindSettingsGenerate(name, type));
          break;
      }
      return void 0;
    };

    Controller.prototype.bindNight = function() {
      var item, plN, place, solved, tr, _i, _j, _len, _len1, _ref, _ref1, _results;
      if (!this.isBindNight) {
        this.isBindNight = 1;
        place = this.view.elements.places[0];
        _ref = place.list;
        _results = [];
        for (plN = _i = 0, _len = _ref.length; _i < _len; plN = ++_i) {
          item = _ref[plN];
          item.actions.unsolve.on('click', plN, (function(_this) {
            return function(event) {
              plN = event.data;
              return _this.model.miss(plN);
            };
          })(this));
          item.actions.solve.on('click', plN, (function(_this) {
            return function(event) {
              plN = event.data;
              return _this.view.attackMode(plN);
            };
          })(this));
          _ref1 = item.actions.treat;
          for (solved = _j = 0, _len1 = _ref1.length; _j < _len1; solved = ++_j) {
            tr = _ref1[solved];
            tr.on('click', {
              plN: plN,
              solved: solved
            }, (function(_this) {
              return function(event) {
                var _ref2;
                _ref2 = event.data, plN = _ref2.plN, solved = _ref2.solved;
                return _this.model.treat(plN, solved);
              };
            })(this));
            void 0;
          }
          item["this"].on('click', "td:not(.actions)", plN, (function(_this) {
            return function(event) {
              plN = event.data;
              return _this.view.selectMode(plN);
            };
          })(this));
          item.id.css('cursor', 'pointer');
          item.name.css('cursor', 'pointer');
          _results.push(void 0);
        }
        return _results;
      }
    };

    return Controller;

  })();

  _Carousel = (function() {
    function _Carousel(elem) {
      this.elem = elem;
    }

    _Carousel.prototype.start = function() {
      return this.elem.carousel("cycle");
    };

    _Carousel.prototype.pause = function() {
      return this.elem.carousel("pause");
    };

    _Carousel.prototype.go = function(num) {
      return this.elem.carousel(num);
    };

    _Carousel.prototype.next = function() {
      return this.elem.carousel("next");
    };

    _Carousel.prototype.prev = function() {
      return this.elem.carousel("prev");
    };

    _Carousel.prototype.hideControls = function() {
      this.elem.find(".carousel-control").fadeOut(500);
      this.elem.find(".carousel-indicators").fadeOut(500);
      return void 0;
    };

    _Carousel.prototype.showControls = function() {
      this.elem.find(".carousel-control").fadeIn(500);
      this.elem.find(".carousel-indicators").fadeIn(500);
      return void 0;
    };

    _Carousel.prototype.overflow = function(st) {
      return this.elem.css({
        "overflow": st
      });
    };

    return _Carousel;

  })();

  ($(document)).ready(function() {
    var controller, model, view;
    console.log("I'm alive!");
    jQuery.fx.interval = 40;
    model = new Model();
    view = new View();
    controller = new Controller();
    model.joinView(view);
    view.joinModel(model);
    view.joinController(controller);
    controller.joinView(view);
    controller.joinModel(model);
    controller.bind();
    window.Model = Model;
    window.View = View;
    window.Controller = Controller;
    window._Carousel = _Carousel;
    window.model = model;
    window.view = view;
    window.controller = controller;
    ($(".navbar-btn")).tooltip();
    ($(".with-tooltip")).tooltip();
    ($("#version")).text(__version__);
    view.updateUI();
    model.addPlayer("Математики");
    model.addPlayer("Лунатики");
    model.addPlayer("Пузатики");
    return void 0;
  });

}).call(this);

//# sourceMappingURL=core.map
