// Generated by CoffeeScript 1.8.0
(function() {
  ($(document)).ready(function() {
    var controller, model, view;
    console.log("I'm alive!");
    jQuery.fx.interval = 40;
    model = new Model();
    view = new View();
    controller = new Controller();
    model.joinView(view);
    view.joinModel(model);
    view.joinController(controller);
    controller.joinView(view);
    controller.joinModel(model);
    controller.bind();
    window.model = model;
    window.view = view;
    window.controller = controller;
    ($(".navbar-btn")).tooltip();
    ($(".with-tooltip")).tooltip();
    ($("#version")).text(__version__);
    view.updateUI();
    return void 0;
  });

}).call(this);

//# sourceMappingURL=core.js.map
