// Generated by CoffeeScript 1.8.0
(function() {
  var A, B, ViewNull, f, model;

  ViewNull = (function() {
    function ViewNull() {}

    ViewNull.prototype.updateUI = function() {};

    return ViewNull;

  })();

  model = new Model();

  window.model = model;

  A = {};

  B = {};

  A.a = 12;

  12;

  _Test_Observer.observe(A, "a", function(a, b, c) {
    return console.log("Must see it once");
  });

  _Test_Observer.observe(B, "a", function(a, b, c) {
    return console.log("Must see it twice");
  });

  A.a = 13;

  B.a = 44;

  _Test_Observer.unobserve(A, "a");

  _Test_Observer.unobserve(A, "x");

  f = function() {
    return A.a = B.a = 333;
  };

  setTimeout(f, 100);

  console.log("==============STATISCTIC================");

  model.addPlayer("test1");

  model.addPlayer("test2");

  model.addPlayer("test3");

  model.startGame();

  console.log(model.players);

  model.players[0].hit(model.players[1]);

  console.groupEnd();

}).call(this);

//# sourceMappingURL=tests.js.map
