// Generated by CoffeeScript 1.10.0
(function() {
  var SavesModal, asc, i;

  i = function(name, color) {
    return $("<i class='material-icons' style=color:" + color + ">").text(name);
  };

  asc = function(id, name, color, callback) {
    id = 1 * id;
    name = name.slice(0);
    return $("<a href='#!' class='secondary-content'>").append(i(name, color)).on('click', function() {
      return callback(id);
    });
  };

  SavesModal = (function() {
    function SavesModal() {
      this.modal = $("#modalSavesBody");
      $("#saveModalBtn").on('click', (function(_this) {
        return function() {
          mgModelSettings.writeSave($("#save_name").val());
          return _this.update();
        };
      })(this));
      this.update();
    }

    SavesModal.prototype.update = function() {
      var id, name, saves;
      saves = Stor.get('saves');
      this.modal.empty();
      this.modal.append((function() {
        var ref, results;
        ref = saves.ids;
        results = [];
        for (id in ref) {
          name = ref[id];
          results.push(this.generateLine(id, name));
        }
        return results;
      }).call(this));
      return $("#save_name").val("");
    };

    SavesModal.prototype.generateLine = function(id, name) {
      return $("<li class='collection-item'>").append($("<div>").text(name).append([
        asc(id, 'delete_forever', 'red', (function(_this) {
          return function(id) {
            mgModelSettings.deleteSave(id);
            return _this.update();
          };
        })(this)), asc(id, 'cloud_upload', 'green', (function(_this) {
          return function(id) {
            mgModelSettings.loadSave(id);
            _this.update();
            mgView.update();
            return mgController.bindPlayersClick();
          };
        })(this))
      ]));
    };

    return SavesModal;

  })();

  window.mgSavesModal = new SavesModal();

}).call(this);

//# sourceMappingURL=saves.js.map
