// Generated by CoffeeScript 1.10.0
(function() {
  window.getValScope = function(val, scope) {
    if (scope[0] > val) {
      return scope[0];
    } else if (scope[1] < val) {
      return scope[1];
    } else {
      return val;
    }
  };

  window.deepCopy = function(v) {
    return $.extend(true, [], v);
  };

  window.btn = function(id, text, color) {
    return $("<a id='" + id + "'>").addClass("waves-effect waves-light btn " + color).text(text);
  };

}).call(this);

//# sourceMappingURL=utils.js.map
