// Generated by CoffeeScript 1.10.0
(function() {
  var Controller;

  Controller = (function() {
    function Controller() {
      $("#modalAddPlayerAgreeBtn").on("click", (function(_this) {
        return function() {
          return _this.addPlayer();
        };
      })(this));
      $("#newPlayerName").keyup((function(_this) {
        return function(e) {
          if (13 === e.keyCode) {
            return _this.addPlayer();
          }
        };
      })(this));
      $("#modeButton").on("click", (function(_this) {
        return function() {
          return _this.changeGameMode();
        };
      })(this));
      mgModelSettings.endDayCallback = (function(_this) {
        return function() {
          return _this.changeGameMode();
        };
      })(this);
    }

    Controller.prototype.addPlayer = function() {
      var name;
      name = $("#newPlayerName").val();
      $("#newPlayerName").val("");
      if (name.length) {
        mgModel.addPlayer(name);
        return mgView.update();
      }
    };

    Controller.prototype.changeGameMode = function() {
      if (isMode(MODE_ADD)) {
        if (mgModel.players.length === 0) {
          Materialize.toast("Вы не добавили ни одного игрока. Нажмите на + на верхней панели, чтобы добавить игроков", 4000, "red darken-4");
        } else {
          setMode(MODE_DAY);
        }
      } else if (isMode(MODE_DAY)) {
        setMode(MODE_NIGHT);
      } else if (isMode(MODE_NIGHT)) {
        setMode(MODE_DAY);
      }
      return mgView.update();
    };

    return Controller;

  })();

  window.mgController = new Controller();

}).call(this);

//# sourceMappingURL=controller.js.map
