// Generated by CoffeeScript 1.8.0
(function() {
  var Saves,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Saves = (function() {
    Saves.protocolVersion = 1;

    function Saves(_at_structure) {
      this.structure = _at_structure;
      this.saves = storage.load('saves');
      if (this.saves && this.saves.version !== this.protocolVersion) {
        this._setDefault();
      }
    }

    Saves.prototype["new"] = function() {
      var id, now;
      now = new Date;
      id = 1488;
      while (__indexOf.call(this.saves.ids, id) >= 0) {
        id = Math.floor(Math.random() * 100000000000000000);
      }
      this.saves.ids[id] = "{#now}";
      _save();
      return _save(id, saveByStructure(this.structure));
    };

    Saves.prototype["delete"] = function(id) {
      delete this.saves.ids[id];
      _save();
      return storage["delete"]("save" + id);
    };

    Saves.prototype.load = function(id) {
      return loadByStructure(this.structure, storage.load("save" + id));
    };

    Saves.prototype._save = function(id, data) {
      if (id == null) {
        id = -1;
      }
      if (data == null) {
        data = void 0;
      }
      switch (id) {
        case -1:
          return storage.save('saves', this.saves);
        default:
          return storage.save("save" + id, data);
      }
    };

    Saves.prototype._setDefault = function() {
      delete this.saves;
      this.saves = {};
      this.saves = {
        version: this.protocolVersion,
        ids: {}
      };
      return this._save();
    };

    return Saves;

  })();

  window.Model.Saves = Saves;

}).call(this);

//# sourceMappingURL=saves.js.map
