// Generated by CoffeeScript 1.8.0
(function() {
  define(["tools/tools"], function(Tools) {
    var Snapshot, getValScope;
    getValScope = Tools.getValScope;
    Snapshot = (function() {
      function Snapshot(_at_obj) {
        this.obj = _at_obj;
        this.datas = [];
        this.current = -1;
        this.add();
        void 0;
      }

      Snapshot.prototype.add = function() {
        this.datas = this.datas.slice(0, this.current + 1);
        this.datas.push(this.obj.serializeToObject());
        return this.current += 1;
      };

      Snapshot.prototype.clear = function() {
        this.current = -1;
        this.datas = [];
        this.add();
        return void 0;
      };

      Snapshot.prototype._load = function(id) {
        if (id == null) {
          id = this.current - 1;
        }
        this.current = getValScope(id, [0, this.data.length]);
        this.obj.deserializeFromObject(this.datas[this.current]);
        return this.current;
      };

      Snapshot.prototype.undo = function() {
        return this._load();
      };

      Snapshot.prototype.redo = function() {
        this.current = getValScope(this.current + 1, [0, this.data.length]);
        return _load(this.current);
      };

      return Snapshot;

    })();
    return Snapshot;
  });

}).call(this);

//# sourceMappingURL=snapshot.js.map
