// Generated by CoffeeScript 1.8.0
(function() {
  var Statistic, getValScope, observer;

  observer = Tools.observer;

  getValScope = Tools.getValScope;

  Statistic = (function() {
    function Statistic(_at_players) {
      this.players = _at_players;
      this.stats = {
        "all_damage": {
          "title": "Урона нанесено: ",
          "value": 0
        },
        "all_tasks": {
          "title": "Сыгранные задачи: ",
          "value": 0
        },
        "all_treat": {
          "title": "Вылеченно здоровья: ",
          "value": 0
        },
        "solve_percent": {
          "title": "Решённые/все задачи: ",
          "value": 0
        }
      };
    }

    Statistic.prototype.binds = function() {
      return this._bind_damage();
    };

    Statistic.prototype._bind_damage = function() {
      var id, player, _ref, _results;
      _ref = this.players;
      _results = [];
      for (id in _ref) {
        player = _ref[id];
        if ("length" !== id) {
          _results.push(observer.observe(player, "health", (function(_this) {
            return function(type, oldValue, newValue) {
              var dmg;
              dmg = getValScope(oldValue - newValue, [0, +Infinity]);
              return _this.stats.all_damage.value += dmg;
            };
          })(this)));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return Statistic;

  })();

  window.Model.Statistic = Statistic;

}).call(this);

//# sourceMappingURL=statistics.js.map
